#!/bin/bash

. ~/.firewall/functions

CONFIG_FW="/root/.fw/$(hostname)-rules"

if [[ ! -f "$CONFIG_FW" ]]; then
  err "could not find $CONFIG_FW file"
  exit 1
else
  msg "using config $CONFIG_FW"
fi

source "$CONFIG_FW"

if [[ ${1:-} ]] && declare -F | cut -d' ' -f3 | fgrep -qx -- "${1:-}"
then
  case "$1" in
    -h|--help|test|save) : ;;
    *) ;;
  esac
  "$@"
else
  main "$@"
fi
