#!/bin/bash

echo "export PATH=\"$HOME/.firewall:\$PATH\"" >> ~/.bashrc

mkdir ~/.fw

cat > ~/.fw/rules-fw <<EOS
# \$WAN is connected to the internet.
IPT=/sbin/iptables
TARGET="/etc/iptables/rules.v4" # if called with '--save'
PRIVATE="10.0.3.0/24"
LXC="lxcbr0" # lxc interface
WAN="eth0" # external interface e.g. eth0
LAN="lxcbr0" # local interface

# Loopback address
LOOP=127.0.0.1
PUBLIC_IP=""
test_run=true
save_rules=false

function rules {
  # Allow local loopback
  ipt -A INPUT -s \$LOOP -j ACCEPT
  ipt -A INPUT -d \$LOOP -j ACCEPT

  # open to the whole world
  ipt -N input_new
  ipt -A input_new -p icmp --icmp-type 8 -j ACCEPT
  # ssh
  open_port tcp 22

}
EOS

echo "complete."
